server:
  port: 8080

kafka:
  brokers:
    - "localhost:9092"
  topic: "products"
  groupid: "product-consumer-group"

mongodb:
  uri: "mongodb://localhost:27017"
  database: "productdb"
  collection: "products"

grpc:
  host: "localhost"
  port: 9080
  timeout: "10s"
