apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kmgm-dev
  namespace: argocd
spec:
  project: default
  source:
    chart: kmgm-app
    repoURL: poc4k-tsnode1b.ovng.dev.myovcloud.com/docker-main
    targetRevision: 0.1.0
    helm:
      releaseName: kmgm-dev
      valuesObject:
        kafka:
          controller:
            persistence:
              size: 3Gi
          broker:
            persistence:
              size: 2Gi
        mongodb:
          persistence:
            size: 2Gi

  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      enabled: false
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
    managedNamespaceMetadata:
      labels:
        policy.sigstore.dev/include: "true"
  ignoreDifferences:
    - group: apps
      kind: Deployment
      jqPathExpressions:
        - .spec.template.spec.containers[]?.image
        - .spec.template.spec.initContainers[]?.image
    - group: apps
      kind: StatefulSet
      jqPathExpressions:
        - .spec.template.spec.containers[]?.image
        - .spec.template.spec.initContainers[]?.image
