---
- name: Sync all RKE2 server configs
  hosts: poc4k_first_server_node
  become: true
  become_user: root
  tasks:
    - name: Sync manifests
      ansible.builtin.copy:
        src: ../../assets/manifests/
        dest: /var/lib/rancher/rke2/server/manifests/
        mode: "0644"
        owner: "{{ ansible_user_id }}"
        group: "{{ ansible_user_gid }}"
