global:
  defaultStorageClass: longhorn-agent-only
  imageRegistry: poc4k-tsnode1b.ovng.dev.myovcloud.com/docker-main
  imagePullSecrets:
    - nexus-regcred
  security:
    allowInsecureImages: true

app:
  replicaCount: 1
  ingressClassName: cilium
  image:
    registry: poc4k-tsnode1b.ovng.dev.myovcloud.com/docker-main
    repository_prefix: kmgm
    tag: 0.1.0
    digest:
      consumer: sha256:ffe886e975a9bd5d149fb72ce170e84c29b10e144943135ba8960251564b7908
      producer: sha256:fc8e25f68b8664a79daf845de23398b235f9b640396660b5d03b6db1b99b7c56
    pullSecrets: nexus-regcred
  issuer:
    email: kngondajob@gmail.com
  resources:
    requests:
      cpu: 250m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 1Gi

kafka:
  networkPolicy:
    enabled: false
  listeners:
    client:
      containerPort: 9092
      protocol: SASL_PLAINTEXT
      name: CLIENT
    controller:
      name: CONTROLLER
      containerPort: 9093
      protocol: SASL_PLAINTEXT
    interbroker:
      containerPort: 9094
      protocol: SASL_PLAINTEXT
      name: INTERNAL
  sasl:
    client:
      users: ["usera"]
      passwords: ["passb"]
  provisioning:
    enabled: true
    topics:
      - name: products

  image:
    repository: kafka
    tag: 4.0.0-debian-12-r10
    # digest: sha256:aa0b2aee8c5610dd1d18d48b4f1df0dbe3267b5d4c338d36c9af9cbf0529c0b0
  controller:
    replicaCount: 3
    persistence:
      enabled: true
      accessModes: [ReadWriteOncePod]
      size: 4Gi
  broker:
    replicaCount: 0
    persistence:
      enabled: true
      accessModes: [ReadWriteOncePod]
      size: 4Gi

  # affinity:
  #   nodeAffinity:
  #     requiredDuringSchedulingIgnoredDuringExecution:
  #       nodeSelectorTerms:
  #       - matchExpressions:
  #         - key: agent
  #           operator: In
  #           values:
  #           - "true"

mongodb:
  architecture: "replicaset"
  resourcesPreset: "medium"
  replicaCount: 1
  image:
    repository: mongodb
    tag: 8.2.1
    # digest: 9cc039b36da327abcbc18743bb13ac601fc20bca851eb7dbea5e7bb0f51b2ae1
  networkPolicy:
    enabled: false

  auth:
    enabled: true
    rootUser: "root"
    rootPassword: "toor"
    usernames: ["usera"]
    passwords: ["passb"]
    databases: ["productdb"]

  # affinity:
  #   nodeAffinity:
  #     requiredDuringSchedulingIgnoredDuringExecution:
  #       nodeSelectorTerms:
  #       - matchExpressions:
  #         - key: agent
  #           operator: In
  #           values:
  #           - "true"

  persistence:
    enabled: true
    accessModes: [ReadWriteOncePod]
    size: 4Gi
  passwordUpdateJob:
    enabled: false
  backup:
    enabled: false
  tls:
    enabled: false
  arbiter:
    enabled: false
  metrics:
    enabled: false
