apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  annotations:
    helmcharts.cattle.io/managed-by: helm-controller
  finalizers:
    - wrangler.cattle.io/on-helm-chart-remove
  name: cert-manager
  namespace: default
spec:
  version: v1.18.2
  chart: cert-manager
  repo: https://charts.jetstack.io
  failurePolicy: abort
  targetNamespace: cert-manager
  createNamespace: true
  valuesContent: |-
    crds:
      enabled: true
    config:
      apiVersion: controller.config.cert-manager.io/v1alpha1
      kind: ControllerConfiguration
      enableGatewayAPI: true
    extraArgs:
      - --enable-gateway-api
