apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  annotations:
    helmcharts.cattle.io/managed-by: helm-controller
  finalizers:
    - wrangler.cattle.io/on-helm-chart-remove
  name: longhorn-install
  namespace: default
spec:
  version: v1.9.1
  chart: longhorn
  repo: https://charts.longhorn.io
  failurePolicy: abort
  targetNamespace: longhorn-system
  createNamespace: true
  valuesContent: |-
    service:
      ui:
        type: NodePort
        nodePort: 31236
    metrics:
      serviceMonitor:
        enabled: true
