# /var/lib/rancher/rke2/server/manifests/rke2-cilium-config.yaml
---
apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: rke2-cilium
  namespace: kube-system
spec:
  valuesContent: |-
    kubeProxyReplacement: true
    k8sServiceHost: "localhost"
    k8sServicePort: "6443"
    # bpf:
    #   masquerade: true
    ingressController:
      enabled: true
      default: true
      loadbalancerMode: shared
      enforceHttps: false
      hostNetwork:
        enabled: true 
        sharedListenerPort: 8079
    gatewayAPI:
      enabled: true
      enableAppProtocol: true
      hostNetwork:
        enabled: true
    loadBalancer:
      l7:
        backend: envoy
    nodePort:
      enabled: true
    encryption: 
      enabled: true
      type: wireguard
    authentication:
      mutual:
        spire:
          enabled: true
          install:
            enabled: true
            server:
              dataStorage:
                storageClass: longhorn-agent-only
              podSecurityContext:
                runAsUser: 0
                fsGroup: 1000
            dataStorage:
              enabled: true
              storageClass: longhorn
    envoy:
      enabled: true
      # log:
      #   defaultLevel: debug
      prometheus: 
        enabled: false
      securityContext:
        capabilities:
          keepCapNetBindService: true
          envoy:
          - NET_ADMIN
          - SYS_ADMIN
          - NET_BIND_SERVICE
    hubble:
      enabled: true
      relay:
        enabled: true
      ui:
        enabled: true
        baseUrl: "/"
        service:
          type: NodePort
        ingress:
          enabled: false
          className: cilium
          hosts:
            - poc4k-tsnode1b.ovng.dev.myovcloud.com
            - poc4k-tsnode2b.ovng.dev.myovcloud.com
            - poc4k-tsnode3b.ovng.dev.myovcloud.com
      metrics:
        enabled:
          - dns:query;ignoreAAAA
          - drop
          - tcp
          - flow
          - http
          - kafka
        serviceMonitor:
          enabled: true
        dashboards:
          enabled: true
