kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: longhorn-agent-only
provisioner: driver.longhorn.io
allowVolumeExpansion: true
reclaimPolicy: Delete
volumeBindingMode: Immediate
parameters:
  numberOfReplicas: "2"
  staleReplicaTimeout: "60"
  fromBackup: ""
  fsType: "ext4"
  nodeSelector: "storage"
  replicaAutoBalance: "least-effort"
  replicaSoftAntiAffinity: "enabled" # for testing purpose