---
- name: Sync all RKE2 server configs
  hosts: poc4k_first_server_node
  become: true
  become_user: root
  tasks:

  - name: Sync assets/rke2-cilium-config.yaml
    ansible.builtin.copy:
      src: ../assets/rke2-cilium-config.yaml
      dest: /var/lib/rancher/rke2/server/manifests/rke2-cilium-config.yaml
      mode: '0644'
      owner: "{{ ansible_user_id }}"
      group: "{{ ansible_user_gid }}"