---
- name: Fetch all RKE2 server configs
  hosts: poc4k_first_server_node
  become: true
  become_user: root
  tasks:

  - name: Fetch kubeconfig
    ansible.builtin.fetch:
      src: /etc/rancher/rke2/rke2.yaml
      dest: ~/.kube/config
      flat: yes

  - name: Fetch assets/server-config.yaml
    ansible.builtin.fetch:
      src: /etc/rancher/rke2/config.yaml
      dest: ../assets/server-config.yaml
      flat: yes

  - name: Fetch manifests
    ansible.builtin.fetch:
      src: /var/lib/rancher/rke2/server/manifests/
      dest: ../assets/manifests/
      flat: yes

- name: Fetch all RKE2 server configs
  hosts: poc4k_agent_nodes
  become: true
  become_user: "{{ ansible_user }}"
  run_once: true
  tasks:

  - name: Fetch assets/agent-config.yaml
    ansible.builtin.fetch:
      src: /etc/rancher/rke2/config.yaml
      dest: ../assets/agent-config.yaml
      flat: yes