---
apiVersion: cilium.io/v2
kind: CiliumClusterwideNetworkPolicy
metadata:
  name: {{ .Release.Name }}-intercept-all-dns
spec:
  endpointSelector:
    matchExpressions:
      - key: "io.kubernetes.pod.namespace"
        operator: "In"
        values:
        - {{ .Release.Namespace }}
      - key: "k8s-app"
        operator: "NotIn"
        values:
        - kube-dns
  egress:
    - toEndpoints:
        - matchLabels:
            io.kubernetes.pod.namespace: kube-system
            k8s-app: kube-dns
      toPorts:
        - ports:
          - port: "53"
            protocol: ANY
          rules:
            dns:
              - matchPattern: "*"

---
apiVersion: cilium.io/v2
kind: CiliumClusterwideNetworkPolicy
metadata:
  name: {{ .Release.Name }}-allow-ingress-egress
spec:
  endpointSelector:
    matchExpressions:
    - key: reserved:ingress
      operator: Exists
  egress:
  - toEndpoints:
    - matchExpressions:
      - key: "io.kubernetes.pod.namespace"
        operator: "In"
        values:
        - {{ .Release.Namespace }}
