---
apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: {{ .Release.Name }}-producer-rules
spec:
  endpointSelector:
    matchLabels:
      {{ include "common.labels.matchLabels" . | nindent 6 }}
      role: producer
  ingress:
    - toPorts:
        - ports:
            - port: "8080"
              protocol: TCP
          rules: 
            http:
            - method: GET
              path: /products
            - method: POST
              path: /products
      fromEndpoints:
      - matchLabels:
          k8s:io.kubernetes.pod.namespace: kube-system
          app.kubernetes.io/name: rke2-ingress-nginx
  egress:
    - toEndpoints:
      - matchLabels:
          k8s:io.kubernetes.pod.namespace: kube-system
          k8s-app: kube-dns
      toPorts:
        - ports:
            - port: "53"
              protocol: ANY
    - toEndpoints:
      - matchLabels:
          {{ include "common.labels.matchLabels" . | nindent 10 }}
          role: consumer
      toPorts:
        - ports:
          - port: "9080"
            protocol: TCP
          rules:
            http:
              - method: POST
                path: /proto.ProductService/GetProducts 
              - method: POST
                path: /proto.ProductService/GetProductByID
    - toEndpoints:
      - matchLabels:
          app.kubernetes.io/name: kafka
          app.kubernetes.io/instance: {{ .Release.Name }}
      toPorts:
        - ports:
          - port: "9092"
            protocol: TCP
          rules:
            kafka:
              - apiKey: createtopic
              - role: produce
                topic: products

---
apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: {{ .Release.Name }}-consumer-rules
spec:
  endpointSelector:
    matchLabels:
      {{ include "common.labels.matchLabels" . | nindent 6 }}
      role: consumer
  ingress:
    - fromEndpoints:
      - matchLabels:
          {{ include "common.labels.matchLabels" . | nindent 10 }}
          role: producer
      toPorts:
        - ports:
          - port: "9080"
            protocol: TCP
          rules:
            http:
              - method: POST
                path: /proto.ProductService/GetProducts 
              - method: POST
                path: /proto.ProductService/GetProductByID
  egress:
    - toEndpoints:
      - matchLabels:
          app.kubernetes.io/name: mongodb
          app.kubernetes.io/instance: {{ .Release.Name }}
      toPorts:
        - ports:
          - port: "27017"
            protocol: TCP
    - toEndpoints:
      - matchLabels:
          k8s:io.kubernetes.pod.namespace: kube-system
          k8s-app: kube-dns
      toPorts:
        - ports:
            - port: "53"
              protocol: ANY
    - toEndpoints:
      - matchLabels:
          app.kubernetes.io/name: kafka
          app.kubernetes.io/instance: {{ .Release.Name }}
      toPorts:
        - ports:
          - port: "9092"
            protocol: TCP
          rules:
            kafka:
              - role: consume
                topic: products
              - apiKey: "listoffsets"