---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-producer
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
    role: producer
spec:
  replicas: {{ .Values.app.replicaCount }}
  selector:
    matchLabels:
      {{- include "common.labels.matchLabels" . | nindent 6 }}
      role: producer
  template:
    metadata:
      labels:
        {{- include "common.labels.standard" . | nindent 8 }}
        role: producer
    spec:
      containers:
      - name: producer
        # image: kng1259/kmgm-producer:latest
        image: "{{ .Values.app.image.registry }}/{{ .Values.app.image.repository_prefix }}-producer:{{ .Values.app.image.tag }}"
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: secret-volume
          readOnly: true
          mountPath: /app/config
      imagePullSecrets: 
      - name: "{{ .Values.app.image.pullSecrets }}"
      volumes:
      - name: secret-volume
        secret:
          secretName: {{ .Release.Name }}-secret

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-consumer
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
    role: consumer
spec:
  replicas: {{ .Values.app.replicaCount }}
  selector:
    matchLabels:
      {{- include "common.labels.matchLabels" . | nindent 6 }}
      role: consumer
  template:
    metadata:
      labels:
        {{- include "common.labels.standard" . | nindent 8 }}
        role: consumer
    spec:
      containers:
      - name: consumer
        image: "{{ .Values.app.image.registry }}/{{ .Values.app.image.repository_prefix }}-consumer:{{ .Values.app.image.tag }}"
        ports:
        - containerPort: 9080
        volumeMounts:
        - name: secret-volume
          readOnly: true
          mountPath: /app/config
      imagePullSecrets: 
      - name: "{{ .Values.app.image.pullSecrets }}"
      volumes:
      - name: secret-volume
        secret:
          secretName: {{ .Release.Name }}-secret

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-producer-test
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
    role: producer-test
spec:
  replicas: {{ .Values.app.replicaCount }}
  selector:
    matchLabels:
      {{- include "common.labels.matchLabels" . | nindent 6 }}
      role: producer-test
  template:
    metadata:
      labels:
        {{- include "common.labels.standard" . | nindent 8 }}
        role: producer-test
    spec:
      containers:
      - name: producer-test
        image: "{{ .Values.app.image.registry }}/{{ .Values.app.image.repository_prefix }}-producer:{{ .Values.app.image.tag }}"
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: secret-volume
          readOnly: true
          mountPath: /app/config
      imagePullSecrets: 
      - name: "{{ .Values.app.image.pullSecrets }}"
      volumes:
      - name: secret-volume
        secret:
          secretName: {{ .Release.Name }}-test-secret