---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-test-secret
  labels:
    {{ include "common.labels.standard" . | nindent 4 }}
stringData:
  config.yaml: |-
    server:
      port: 8080
      route: products-test
    kafka:
      enabled: true
      brokers:
        - "{{ .Release.Name }}-kafka:9092"
      username: {{ first .Values.kafka.sasl.client.users }}
      password: {{ first .Values.kafka.sasl.client.passwords }}
      topic: "products"
      groupid: "product-consumer-group"
    mongodb:
      uri: "mongodb://{{ first .Values.mongodb.auth.usernames }}:{{ first .Values.mongodb.auth.passwords }}@{{ .Release.Name }}-mongodb-headless:27017/{{ first .Values.mongodb.auth.databases }}"
      database: {{ first .Values.mongodb.auth.databases }} 
      collection: "products"
    grpc:
      host: "{{ .Release.Name }}-consumer-service"
      port: 9080
      timeout: "10s"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-producer-test
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
    role: producer-test
spec:
  replicas: {{ .Values.app.replicaCount }}
  selector:
    matchLabels:
      {{- include "common.labels.matchLabels" . | nindent 6 }}
      role: producer-test
  template:
    metadata:
      labels:
        {{- include "common.labels.standard" . | nindent 8 }}
        role: producer-test
    spec:
      containers:
      - name: producer-test
        image: kng1259/kmgm-producer:latest
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: secret-volume
          readOnly: true
          mountPath: /app/config
      volumes:
      - name: secret-volume
        secret:
          secretName: {{ .Release.Name }}-test-secret

---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-producer-test-service
  labels:
    {{ include "common.labels.standard" . | nindent 4 }}
    role: producer-test
spec:
  type: NodePort
  selector:
    {{ include "common.labels.matchLabels" . | nindent 4 }}
    role: producer-test
  ports:
  - port: 8080
    targetPort: 8080

---
apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: {{ .Release.Name }}-producer-test-rules
spec:
  endpointSelector:
    matchLabels:
      {{ include "common.labels.matchLabels" . | nindent 6 }}
      role: producer-test
  ingress:
  - fromEndpoints:
    - {}
    - matchExpressions:
      - key: k8s:io.kubernetes.pod.namespace 
        operator: In
        values: 
        - kube-system
  egress:
  - toEndpoints:
    - {}

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-producer-test-ingress
  labels:
    {{ include "common.labels.standard" . | nindent 4 }}
    role: producer-test
  annotations:
    cert-manager.io/cluster-issuer: selfsigned-cluster-issuer
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /products
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}-producer-test-service
                port:
                  number: 8080
  tls:
    - hosts:
        - poc4k-tsnode1b.ovng.dev.myovcloud.com
        - poc4k-tsnode2b.ovng.dev.myovcloud.com
        - poc4k-tsnode3b.ovng.dev.myovcloud.com
      secretName: {{ .Release.Name }}-tls
