apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
  labels:
    {{ include "common.labels.standard" . | nindent 4 }}
stringData:
  config.yaml: |-
    server:
      port: 8080
      route: products/
    kafka:
      enabled: true
      brokers:
        - "{{ .Release.Name }}-kafka:9092"
      username: {{ first .Values.kafka.sasl.client.users }}
      password: {{ first .Values.kafka.sasl.client.passwords }}
      topic: "products"
      groupid: "product-consumer-group"
    mongodb:
      uri: "mongodb://{{ first .Values.mongodb.auth.usernames }}:{{ first .Values.mongodb.auth.passwords }}@{{ .Release.Name }}-mongodb-headless:27017/{{ first .Values.mongodb.auth.databases }}"
      database: {{ first .Values.mongodb.auth.databases }} 
      collection: "products"
    grpc:
      host: "{{ .Release.Name }}-consumer-service"
      port: 9080
      timeout: "10s"

