---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-producer-service
  labels:
    {{ include "common.labels.standard" . | nindent 4 }}
    role: producer
spec:
  type: NodePort
  selector:
    {{ include "common.labels.matchLabels" . | nindent 4 }}
    role: producer
  ports:
  - port: 8080
    targetPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-consumer-service
  labels:
    {{ include "common.labels.standard" . | nindent 4 }}
    role: consumer
spec:
  type: ClusterIP
  selector:
    {{ include "common.labels.matchLabels" . | nindent 4 }}
    role: consumer
  ports:
  - port: 9080
    targetPort: 9080