apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd
resources:
  - namespace.yaml
  - https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/ha/install.yaml
  - argocd-repositories.yaml
patches:
  - path: argocd-tls-certs-cm.yaml
  - path: service.yaml
