apiVersion: v1
kind: Service
metadata:
  name: argocd-server
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8080
      nodePort: 31337
    - name: https
      port: 443
      protocol: TCP
      targetPort: 8080
      nodePort: 31237
  type: NodePort
