---
- name: Sync configs
  hosts: poc4k_gitlab
  become: true
  become_user: root
  tasks:
    - name: Sync config
      ansible.builtin.copy:
        src: ../../assets/gitlab.rb
        dest: /etc/gitlab/gitlab.rb
        mode: "0500"
        owner: "root"
        group: "{{ ansible_user_gid }}"

    - name: Reconfig
      ansible.builtin.command: gitlab-ctl reconfigure
